name: Node.js With Docker

on:
    push:
      branches:
        - "docker"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
      strategy:
        matrix:
          version: [14, 16, 18]
      runs-on: ubuntu-latest
      steps:
        - name: 'checkout'
          uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.version }}

        - name: Install dependencies
          run: npm install
        - name: Run Tests
          run: npm run test
  build-docker:
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GH }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Deploy
        if: github.ref == 'refs/heads/docker'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
